import 'core-js'
import React from 'react'

/*import './design-library'
import './in-page-ui'
// import './ribbon'
// import './sidebar'
import './sync'
import './subscribe'
import './backup'
import './icons'
import './tagsCurrent'
import './tagsRefactored'
import './popup-components'
import './other'
import './copy-paster'*/
import './annotations-sidebar'
import './copy-paster'
import './sharing'
import './dashboard-refactor/header'
