import 'core-js'
import React from 'react'

/*import './design-library'
import './in-page-ui'
// import './ribbon'
// import './sidebar'
import './sync'
import './subscribe'
import './backup'
import './icons'
import './tagsCurrent'
import './tagsRefactored'
import './popup-components'
import './other'
import './copy-paster'
import './annotations-sidebar'
import './copy-paster'
import './sharing'*/
import './dashboard-refactor/header/sidebar-header'
import './dashboard-refactor/header/sidebar-toggle'
import './dashboard-refactor/header/search-bar'
import './dashboard-refactor/header/sync-status-menu'
import './dashboard-refactor/header/filters-bar'
import './dashboard-refactor/header/'
import './dashboard-refactor/lists-sidebar/list-item'
import './dashboard-refactor/lists-sidebar/lists-sidebar-group'
import './dashboard-refactor/lists-sidebar/lists-sidebar-search-bar'
import './dashboard-refactor/lists-sidebar/lists-sidebar'
