export const API_HOST =
    'https://a8495szyaa.execute-api.eu-central-1.amazonaws.com/' +
    (process.env.NODE_ENV === 'production' ? 'production' : 'staging')

export const MapEventTypeToInt = {
    successful_search: 1,
    paginate_search: 2,
    unsuccessful_search: 3,
    datepicker_by_dropdown_start_date: 4,
    datepicker_clear_start_date: 5,
    datepicker_by_dropdown_end_date: 6,
    datepicker_clear_end_date: 7,
    successful_search_with_tag: 8,
    successful_search_with_domain: 9,
    unsuccessful_search_with_bm: 10,
    successful_search_with_bm: 11,
    add_tag: 12,
    delete_tag: 13,
    delete_result: 14,
    create_result_bookmark: 15,
    remove_result_bookmark: 16,
    create_browser_bookmark: 17,
    remove_browser_bookmark: 18,
    create_popup_bookmark: 19,
    remove_popup_bookmark: 20,
    add_popup_tag: 21,
    delete_popup_tag: 22,
    blacklist_site: 23,
    blacklist_domain: 24,
    remove_blacklist_entry: 25,
    'change_tracking_pref_opt-out': 26,
    'change_tracking_pref_opt-in': 27,
    start_import: 28,
    pause_import: 29,
    resume_import: 30,
    cancel_import: 31,
    finish_import: 32,
    search_popup: 33,
    successful_omnibar_search: 34,
    unsuccessful_omnibar_search: 35,
    datepicker_by_nlp_start_date: 36,
    datepicker_by_nlp_end_date: 37,
}
