import browser from 'webextension-polyfill'

export const addPeople = browser.runtime.getURL('/img/addPeople.svg')
export const arrowDown = browser.runtime.getURL('/img/arrowDown.svg')
export const arrowLeft = browser.runtime.getURL('/img/arrowLeft.svg')
export const arrowRight = browser.runtime.getURL('/img/arrowRight.svg')
export const arrowUp = browser.runtime.getURL('/img/arrow-up.svg')
export const atSign = browser.runtime.getURL('/img/atSign.svg')
export const backup = browser.runtime.getURL('/img/backup.svg')
export const bell = null
export const block = browser.runtime.getURL('/img/block.svg')
export const blueRoundCheck = browser.runtime.getURL('/img/blueRoundCheck.svg')
export const boldIcon = browser.runtime.getURL('/img/boldIcon.svg')
export const bulletListIcon = browser.runtime.getURL('/img/bulletListIcon.svg')
export const chatWithUs = browser.runtime.getURL('/img/chatWithUs.svg')
export const check = browser.runtime.getURL('/img/check.svg')
export const checkedRound = null
export const checkRound = browser.runtime.getURL('/img/checkRound.svg')
export const clock = browser.runtime.getURL('/img/clock.svg')
export const coilIcon = null
export const collectionsEmpty = browser.runtime.getURL('/img/spaceEmpty.svg')
export const collectionsFull = browser.runtime.getURL('/img/spaceFull.svg')
export const command = browser.runtime.getURL('/img/command.svg')
export const comment = browser.runtime.getURL('/img/comment_full.svg')
export const commentAdd = browser.runtime.getURL('/img/comment_add.svg')
export const commentFull = browser.runtime.getURL('/img/comment_full.svg')
export const compress = browser.runtime.getURL('/img/compress.svg')
export const copy = browser.runtime.getURL('/img/copy.svg')
export const cursor = browser.runtime.getURL('/img/cursor.svg')
export const calendar = browser.runtime.getURL('/img/calendar.svg')
export const date = browser.runtime.getURL('/img/date.svg')
export const discord = browser.runtime.getURL('/img/discord.svg')
export const slack = browser.runtime.getURL('/img/slack.svg')
export const dots = browser.runtime.getURL('/img/3dots.svg')
export const doubleArrow = browser.runtime.getURL('/img/doubleArrow.svg')
export const dropImage = browser.runtime.getURL('/img/dropImage.svg')
export const edit = browser.runtime.getURL('/img/edit.svg')
export const emptyCircle = browser.runtime.getURL('/img/emptyCircle.svg')
export const expand = browser.runtime.getURL('/img/expand.svg')
export const feed = browser.runtime.getURL('/img/feed.svg')
export const file = browser.runtime.getURL('/img/file.svg')
export const filePDF = browser.runtime.getURL('/img/file-pdf.svg')
export const filterIcon = browser.runtime.getURL('/img/filterIcon.svg')
export const folder = browser.runtime.getURL('/img/folder.svg')
export const fullPageReading = browser.runtime.getURL(
    '/img/fullPageReading.svg',
)
export const globe = browser.runtime.getURL('/img/globe.svg')
export const goTo = browser.runtime.getURL('/img/open.svg')
export const h1Icon = browser.runtime.getURL('/img/h1Icon.svg')
export const h2Icon = browser.runtime.getURL('/img/h2Icon.svg')
export const hamburger = browser.runtime.getURL('/img/hamburger.svg')
export const heartEmpty = browser.runtime.getURL('/img/heart_empty.svg')
export const heartFull = browser.runtime.getURL('/img/heart_full.svg')
export const helpIcon = browser.runtime.getURL('/img/help.svg')
export const highlight = browser.runtime.getURL('/img/highlights.svg')
export const highlighterEmpty = browser.runtime.getURL('/img/highlightOff.svg')
export const highlighterFull = browser.runtime.getURL('/img/highlightOn.svg')
export const imageIcon = browser.runtime.getURL('/img/imageIcon.svg')
export const imports = browser.runtime.getURL('/img/import.svg')
export const inbox = browser.runtime.getURL('/img/inbox.svg')
export const info = browser.runtime.getURL('/img/infoIcon.svg')
export const integrate = browser.runtime.getURL('/img/integrate.svg')
export const invite = browser.runtime.getURL('/img/invite.svg')
export const italicIcon = browser.runtime.getURL('/img/italicIcon.svg')
export const link = browser.runtime.getURL('/img/link.svg')
export const linuxLogo = browser.runtime.getURL('/img/linux_logo.svg')
export const lock = browser.runtime.getURL('/img/lock.svg')
export const lockFine = browser.runtime.getURL('/img/lockFine.svg')
export const login = browser.runtime.getURL('/img/login.svg')
export const logoHorizontal = browser.runtime.getURL(
    '/img/memexLogoHorizontal.png',
)
export const logoNoText = browser.runtime.getURL('/img/memexLogo.svg')
export const logout = browser.runtime.getURL('/img/logout.svg')
export const longArrow = browser.runtime.getURL('/img/longArrowLeft.svg')
export const longArrowRight = browser.runtime.getURL('/img/longArrowRight.svg')
export const macLogo = browser.runtime.getURL('/img/apple_logo.svg')
export const mail = browser.runtime.getURL('/img/mail.svg')
export const mediumLogo = browser.runtime.getURL('/img/medium-logo.svg')
export const memexLogoGrey = browser.runtime.getURL('/img/memexLogoGrey.svg')
export const multiEdit = browser.runtime.getURL('/img/multiEdits.svg')
export const newFeed = null
export const numberedListIcon = browser.runtime.getURL(
    '/img/numberedListIcon.svg',
)
export const openSidebar = browser.runtime.getURL('/img/openSidebar.svg')
export const pause = browser.runtime.getURL('/img/pause.svg')
export const pdf = browser.runtime.getURL('/img/file-pdf.svg')
export const peopleFine = browser.runtime.getURL('/img/peopleFine.svg')
export const peoplePlusFine = browser.runtime.getURL('/img/peoplePlusFine.svg')
export const personFine = browser.runtime.getURL('/img/personFine.svg')
export const phone = browser.runtime.getURL('/img/phone.svg')
export const pin = browser.runtime.getURL('/img/pin.svg')
export const play = browser.runtime.getURL('/img/play.svg')
export const playFull = browser.runtime.getURL('/img/playFull.svg')
export const plus = browser.runtime.getURL('/img/plus.svg')
export const plusIcon = browser.runtime.getURL('/img/followedSpace.svg')
export const quickActionRibbon = browser.runtime.getURL(
    '/img/quickActionRibbon.svg',
)
export const readwise = browser.runtime.getURL('/img/readwise.svg')
export const redo = browser.runtime.getURL('/img/redo.svg')
export const reload = browser.runtime.getURL('/img/reload.svg')
export const remove = browser.runtime.getURL('/img/remove.svg')
export const removeX = browser.runtime.getURL('/img/removeX.svg')
export const ribbonOff = browser.runtime.getURL('/img/ribbonOff.svg')
export const ribbonOn = browser.runtime.getURL('/img/ribbonOn.svg')
export const sadFace = browser.runtime.getURL('/img/sadFace.svg')
export const saveIcon = browser.runtime.getURL('/img/saveIcon.svg')
export const searchIcon = browser.runtime.getURL('/img/search.svg')
export const settings = browser.runtime.getURL('/img/settings.svg')
export const share = browser.runtime.getURL('/img/share.svg')
export const shared = browser.runtime.getURL('/img/shared.svg')
export const sharedProtected = browser.runtime.getURL(
    '/img/sharedprotected.svg',
)
export const shareEmpty = browser.runtime.getURL('/img/shareEmpty.svg')
export const shareWhite = browser.runtime.getURL('/img/shareWhite.svg')
export const shield = browser.runtime.getURL('/img/shield.svg')
export const sidebarIcon = browser.runtime.getURL('/img/sidebarOn.svg')
export const sideBySide = browser.runtime.getURL('/img/sideBySide.svg')
export const smileFace = browser.runtime.getURL('/img/smileFace.svg')
export const sort = browser.runtime.getURL('/img/sort.svg')
export const spotifyLogo = browser.runtime.getURL('/img/spotify-logo.svg')
export const stars = browser.runtime.getURL('/img/stars.svg')
export const stop = browser.runtime.getURL('/img/stop.svg')
export const strikethroughIcon = browser.runtime.getURL(
    '/img/strikethroughIcon.svg',
)
export const substackLogo = browser.runtime.getURL('/img/substack-logo.svg')
export const sunrise = browser.runtime.getURL('/img/sunrise.svg')
export const tagEmpty = browser.runtime.getURL('/img/tag_empty.svg')
export const tagFull = browser.runtime.getURL('/img/tag_full.svg')
export const threadIcon = null
export const timestampIcon = browser.runtime.getURL('/img/timestampIcon.svg')
export const tooltipOff = browser.runtime.getURL('/img/tooltipOff.svg')
export const tooltipOn = browser.runtime.getURL('/img/tooltipOn.svg')
export const trash = browser.runtime.getURL('/img/trash.svg')
export const triangle = browser.runtime.getURL('/img/chevron-down.svg')
export const twitter = browser.runtime.getURL('/img/twitter.svg')
export const twitterLogo = browser.runtime.getURL('/img/twitter-logo.svg')
export const telegram = browser.runtime.getURL('/img/telegram.svg')
export const googleLogo = browser.runtime.getURL('/img/googleLogo.svg')
export const twitterThin = browser.runtime.getURL('/img/youtube-logo.svg')
export const warning = browser.runtime.getURL('/img/alertRound.svg')
export const webMonetizationLogo = browser.runtime.getURL(
    '/img/web-monetization-logo.svg',
)
export const webMonetizationLogoConfirmed = browser.runtime.getURL(
    '/img/web-monetization-logo-confirmed.svg',
)
export const winLogo = browser.runtime.getURL('/img/windows_logo.svg')
export const youtubeLogo = browser.runtime.getURL('/img/youtube-logo.svg')
export const reply = browser.runtime.getURL('/img/reply.svg')
export const openAI = browser.runtime.getURL('/img/openAI.svg')
export const openAIicon = browser.runtime.getURL('/img/openAIicon.svg')
export const bulletPoint = browser.runtime.getURL('/img/bulletPoint.svg')
export const sun = browser.runtime.getURL('/img/sun.svg')
export const moon = browser.runtime.getURL('/img/moon.svg')
export const cameraIcon = browser.runtime.getURL('/img/cameraIcon.svg')
export const memexIconDarkMode = browser.runtime.getURL(
    '/img/memexIconDarkMode.svg',
)
export const memexIconLightMode = browser.runtime.getURL(
    '/img/memexIcoLightkMode.svg',
)
export const obsidianLogo = browser.runtime.getURL('/img/obsidianLogo.svg')
export const logseqLogo = browser.runtime.getURL('/img/logseqLogo.svg')
export const rectangleDraw = browser.runtime.getURL('/img/rectangleDraw.svg')
export const local = browser.runtime.getURL('/img/local.svg')
export const key = browser.runtime.getURL('/img/key.svg')
export const spread = browser.runtime.getURL('/img/spread.svg')
export const dragList = browser.runtime.getURL('/img/dragList.svg')
export const memexIconOnly = browser.runtime.getURL('/img/memexIconOnly.svg')
export const move = browser.runtime.getURL('/img/move.svg')
export const browserIcon = browser.runtime.getURL(
    '/img/browserIcons/logo-48.png',
)
