export const addPeople = chrome.runtime.getURL('/img/addPeople.svg')
export const arrowDown = chrome.runtime.getURL('/img/arrowDown.svg')
export const arrowLeft = chrome.runtime.getURL('/img/arrowLeft.svg')
export const arrowRight = chrome.runtime.getURL('/img/arrowRight.svg')
export const arrowUp = chrome.runtime.getURL('/img/arrow-up.svg')
export const atSign = chrome.runtime.getURL('/img/atSign.svg')
export const backup = chrome.runtime.getURL('/img/backup.svg')
export const bell = null
export const block = chrome.runtime.getURL('/img/block.svg')
export const blueRoundCheck = chrome.runtime.getURL('/img/blueRoundCheck.svg')
export const boldIcon = chrome.runtime.getURL('/img/boldIcon.svg')
export const bulletListIcon = chrome.runtime.getURL('/img/bulletListIcon.svg')
export const chatWithUs = chrome.runtime.getURL('/img/chatWithUs.svg')
export const check = chrome.runtime.getURL('/img/check.svg')
export const checkedRound = null
export const checkRound = chrome.runtime.getURL('/img/checkRound.svg')
export const clock = chrome.runtime.getURL('/img/clock.svg')
export const coilIcon = null
export const collectionsEmpty = chrome.runtime.getURL('/img/spaceEmpty.svg')
export const collectionsFull = chrome.runtime.getURL('/img/spaceFull.svg')
export const command = chrome.runtime.getURL('/img/command.svg')
export const comment = chrome.runtime.getURL('/img/comment_full.svg')
export const commentAdd = chrome.runtime.getURL('/img/comment_add.svg')
export const commentFull = chrome.runtime.getURL('/img/comment_full.svg')
export const compress = chrome.runtime.getURL('/img/compress.svg')
export const copy = chrome.runtime.getURL('/img/copy.svg')
export const cursor = chrome.runtime.getURL('/img/cursor.svg')
export const calendar = chrome.runtime.getURL('/img/calendar.svg')
export const date = chrome.runtime.getURL('/img/date.svg')
export const discord = chrome.runtime.getURL('/img/discord.svg')
export const slack = chrome.runtime.getURL('/img/slack.svg')
export const dots = chrome.runtime.getURL('/img/3dots.svg')
export const doubleArrow = chrome.runtime.getURL('/img/doubleArrow.svg')
export const dropImage = chrome.runtime.getURL('/img/dropImage.svg')
export const edit = chrome.runtime.getURL('/img/edit.svg')
export const emptyCircle = chrome.runtime.getURL('/img/emptyCircle.svg')
export const expand = chrome.runtime.getURL('/img/expand.svg')
export const feed = chrome.runtime.getURL('/img/feed.svg')
export const file = chrome.runtime.getURL('/img/file.svg')
export const filePDF = chrome.runtime.getURL('/img/file-pdf.svg')
export const filterIcon = chrome.runtime.getURL('/img/filterIcon.svg')
export const folder = chrome.runtime.getURL('/img/folder.svg')
export const fullPageReading = chrome.runtime.getURL('/img/fullPageReading.svg')
export const globe = chrome.runtime.getURL('/img/globe.svg')
export const goTo = chrome.runtime.getURL('/img/open.svg')
export const h1Icon = chrome.runtime.getURL('/img/h1Icon.svg')
export const h2Icon = chrome.runtime.getURL('/img/h2Icon.svg')
export const hamburger = chrome.runtime.getURL('/img/hamburger.svg')
export const heartEmpty = chrome.runtime.getURL('/img/heart_empty.svg')
export const heartFull = chrome.runtime.getURL('/img/heart_full.svg')
export const helpIcon = chrome.runtime.getURL('/img/help.svg')
export const highlight = chrome.runtime.getURL('/img/highlights.svg')
export const highlighterEmpty = chrome.runtime.getURL('/img/highlightOff.svg')
export const highlighterFull = chrome.runtime.getURL('/img/highlightOn.svg')
export const imageIcon = chrome.runtime.getURL('/img/imageIcon.svg')
export const imports = chrome.runtime.getURL('/img/import.svg')
export const inbox = chrome.runtime.getURL('/img/inbox.svg')
export const info = chrome.runtime.getURL('/img/infoIcon.svg')
export const integrate = chrome.runtime.getURL('/img/integrate.svg')
export const invite = chrome.runtime.getURL('/img/invite.svg')
export const italicIcon = chrome.runtime.getURL('/img/italicIcon.svg')
export const link = chrome.runtime.getURL('/img/link.svg')
export const linuxLogo = chrome.runtime.getURL('/img/linux_logo.svg')
export const lock = chrome.runtime.getURL('/img/lock.svg')
export const lockFine = chrome.runtime.getURL('/img/lockFine.svg')
export const login = chrome.runtime.getURL('/img/login.svg')
export const logoHorizontal = chrome.runtime.getURL(
    '/img/memexLogoHorizontal.png',
)
export const logoNoText = chrome.runtime.getURL('/img/memexLogo.svg')
export const logout = chrome.runtime.getURL('/img/logout.svg')
export const longArrow = chrome.runtime.getURL('/img/longArrowLeft.svg')
export const longArrowRight = chrome.runtime.getURL('/img/longArrowRight.svg')
export const macLogo = chrome.runtime.getURL('/img/apple_logo.svg')
export const mail = chrome.runtime.getURL('/img/mail.svg')
export const mediumLogo = chrome.runtime.getURL('/img/medium-logo.svg')
export const memexLogoGrey = chrome.runtime.getURL('/img/memexLogoGrey.svg')
export const multiEdit = chrome.runtime.getURL('/img/multiEdits.svg')
export const newFeed = null
export const numberedListIcon = chrome.runtime.getURL(
    '/img/numberedListIcon.svg',
)
export const openSidebar = chrome.runtime.getURL('/img/openSidebar.svg')
export const pause = chrome.runtime.getURL('/img/pause.svg')
export const pdf = chrome.runtime.getURL('/img/file-pdf.svg')
export const peopleFine = chrome.runtime.getURL('/img/peopleFine.svg')
export const peoplePlusFine = chrome.runtime.getURL('/img/peoplePlusFine.svg')
export const personFine = chrome.runtime.getURL('/img/personFine.svg')
export const phone = chrome.runtime.getURL('/img/phone.svg')
export const pin = chrome.runtime.getURL('/img/pin.svg')
export const play = chrome.runtime.getURL('/img/play.svg')
export const playFull = chrome.runtime.getURL('/img/playFull.svg')
export const plus = chrome.runtime.getURL('/img/plus.svg')
export const plusIcon = chrome.runtime.getURL('/img/followedSpace.svg')
export const quickActionRibbon = chrome.runtime.getURL(
    '/img/quickActionRibbon.svg',
)
export const readwise = chrome.runtime.getURL('/img/readwise.svg')
export const redo = chrome.runtime.getURL('/img/redo.svg')
export const reload = chrome.runtime.getURL('/img/reload.svg')
export const remove = chrome.runtime.getURL('/img/remove.svg')
export const removeX = chrome.runtime.getURL('/img/removeX.svg')
export const ribbonOff = chrome.runtime.getURL('/img/ribbonOff.svg')
export const ribbonOn = chrome.runtime.getURL('/img/ribbonOn.svg')
export const sadFace = chrome.runtime.getURL('/img/sadFace.svg')
export const saveIcon = chrome.runtime.getURL('/img/saveIcon.svg')
export const searchIcon = chrome.runtime.getURL('/img/search.svg')
export const settings = chrome.runtime.getURL('/img/settings.svg')
export const share = chrome.runtime.getURL('/img/share.svg')
export const shared = chrome.runtime.getURL('/img/shared.svg')
export const sharedProtected = chrome.runtime.getURL('/img/sharedprotected.svg')
export const shareEmpty = chrome.runtime.getURL('/img/shareEmpty.svg')
export const shareWhite = chrome.runtime.getURL('/img/shareWhite.svg')
export const shield = chrome.runtime.getURL('/img/shield.svg')
export const sidebarIcon = chrome.runtime.getURL('/img/sidebarOn.svg')
export const sideBySide = chrome.runtime.getURL('/img/sideBySide.svg')
export const smileFace = chrome.runtime.getURL('/img/smileFace.svg')
export const sort = chrome.runtime.getURL('/img/sort.svg')
export const spotifyLogo = chrome.runtime.getURL('/img/spotify-logo.svg')
export const stars = chrome.runtime.getURL('/img/stars.svg')
export const stop = chrome.runtime.getURL('/img/stop.svg')
export const strikethroughIcon = chrome.runtime.getURL(
    '/img/strikethroughIcon.svg',
)
export const substackLogo = chrome.runtime.getURL('/img/substack-logo.svg')
export const sunrise = chrome.runtime.getURL('/img/sunrise.svg')
export const tagEmpty = chrome.runtime.getURL('/img/tag_empty.svg')
export const tagFull = chrome.runtime.getURL('/img/tag_full.svg')
export const threadIcon = null
export const timestampIcon = chrome.runtime.getURL('/img/timestampIcon.svg')
export const tooltipOff = chrome.runtime.getURL('/img/tooltipOff.svg')
export const tooltipOn = chrome.runtime.getURL('/img/tooltipOn.svg')
export const trash = chrome.runtime.getURL('/img/trash.svg')
export const triangle = chrome.runtime.getURL('/img/chevron-down.svg')
export const twitter = chrome.runtime.getURL('/img/twitter.svg')
export const twitterLogo = chrome.runtime.getURL('/img/twitter-logo.svg')
export const blueskyLogo = chrome.runtime.getURL('/img/bluesky-logo.svg')
export const telegram = chrome.runtime.getURL('/img/telegram.svg')
export const googleLogo = chrome.runtime.getURL('/img/googleLogo.svg')
export const twitterThin = chrome.runtime.getURL('/img/youtube-logo.svg')
export const warning = chrome.runtime.getURL('/img/alertRound.svg')
export const webMonetizationLogo = chrome.runtime.getURL(
    '/img/web-monetization-logo.svg',
)
export const webMonetizationLogoConfirmed = chrome.runtime.getURL(
    '/img/web-monetization-logo-confirmed.svg',
)
export const winLogo = chrome.runtime.getURL('/img/windows_logo.svg')
export const youtubeLogo = chrome.runtime.getURL('/img/youtube-logo.svg')
export const reply = chrome.runtime.getURL('/img/reply.svg')
export const openAI = chrome.runtime.getURL('/img/openAI.svg')
export const openAIicon = chrome.runtime.getURL('/img/openAIicon.svg')
export const bulletPoint = chrome.runtime.getURL('/img/bulletPoint.svg')
export const sun = chrome.runtime.getURL('/img/sun.svg')
export const moon = chrome.runtime.getURL('/img/moon.svg')
export const cameraIcon = chrome.runtime.getURL('/img/cameraIcon.svg')
export const memexIconDarkMode = chrome.runtime.getURL(
    '/img/memexIconDarkMode.svg',
)
export const memexIconLightMode = chrome.runtime.getURL(
    '/img/memexIcoLightkMode.svg',
)
export const obsidianLogo = chrome.runtime.getURL('/img/obsidianLogo.svg')
export const logseqLogo = chrome.runtime.getURL('/img/logseqLogo.svg')
export const rectangleDraw = chrome.runtime.getURL('/img/rectangleDraw.svg')
export const local = chrome.runtime.getURL('/img/local.svg')
export const key = chrome.runtime.getURL('/img/key.svg')
export const spread = chrome.runtime.getURL('/img/spread.svg')
export const dragList = chrome.runtime.getURL('/img/dragList.svg')
export const memexIconOnly = chrome.runtime.getURL('/img/memexIconOnly.svg')
export const move = chrome.runtime.getURL('/img/move.svg')
export const enter = chrome.runtime.getURL('/img/enter.svg')
export const browserIcon = chrome.runtime.getURL(
    '/img/browserIcons/logo-48.png',
)
