import { MemexTheme as Theme } from '@worldbrain/memex-common/lib/common-ui/styles/types'
import * as icons from 'src/common-ui/components/design-library/icons'

export const theme: Theme = {
    spacing: {
        none: '0',
        smallest: '0.25rem',
        small: '0.5rem',
        medium: '1rem',
        large: '1.5rem',
        largest: '3rem',
    },
    colors: {
        background: 'white',
        warning: 'red',
        primary: '#3a2f45',
        subText: '#aeaeae',
        purple: '#347AE2',
        white: '#fff',
        lightgrey: '#f0f0f0',
        darkgrey: '#545454',
        secondary: '#5cd9a6',
        grey: '#e0e0e0',
        black: '#000',
        overlay: {
            background: 'rgba(0, 0, 0, 0.1)',
            dialog: 'white',
        },
        lightblack: '#292C38',
        lineGrey: '#ECEFF4',
        lineLightGrey: '#E0E5ED',
        iconColor: '#96A0B5',
        lightHover: '#F4F9FF',
        backgroundHighlight: '#e6f1ff',
        darkhover: '#E5F0FF',
        normalText: '#73778B',
        darkerText: '#292C38',
        lighterText: '#96A0B5',
        backgroundColor: '#F8FBFF',
        backgroundColorDarker: '#e5f0ff80',
        darkerBlue: '#5E6278',
        blue: '2563EB',
    },
    fonts: {
        primary: '"Inter", sans-serif',
        secondary: '"Inter", sans-serif',
    },
    fontWeights: {
        normal: 400,
        bold: 700,
    },
    hoverBackgrounds: {
        primary: '#e0e0e0',
    },
    borderRadii: {
        default: '3px',
    },
    fontSizes: {
        header: '20px',
        listTitle: '16px',
        url: '14px',
        text: '12px',
        smallText: '8px',
    },
    lineHeights: {
        header: '30px',
        listTitle: '24px',
        url: '21px',
        text: '18px',
        smallText: '12px',
    },
    zIndices: {
        overlay: 5000,
    },
    icons: {
        copy: icons.copy,
        removeX: icons.removeX,
        hamburger: icons.hamburger,
        addPeople: icons.addPeople,
        checkRound: icons.checkRound,
        alertRound: icons.alertRound,
        triangle: icons.triangle,
        lock: icons.lock,
        plus: icons.plus,
        goTo: icons.goTo,
        person: icons.person,
        shared: icons.shared,
        shareEmpty: icons.shareEmpty,
        check: icons.check,
        comment: icons.commentFull,
        commentEmpty: icons.commentEmpty,
        people: icons.shared,
        plusIcon: icons.plus,
        webLogo: icons.webLogo,
        mediumLogo: icons.mediumLogo,
        twitterLogo: icons.twitterLogo,
        substackLogo: icons.substackLogo,
        webMonetizationLogo: icons.webMonetizationLogo,
        webMonetizationLogoConfirmed: icons.webMonetizationLogoConfirmed,
    },
}
