import 'babel-polyfill'
import 'src/activity-logger/content_script'
import 'src/page-analysis/content_script'
import 'src/search-injection/content_script'
import 'src/content-tooltip/content_script'
import 'src/direct-linking/content_script'
import 'src/sidebar-overlay/content_script'
import 'src/backup/content_script'
